pipeline {
    agent any
    parameters {
        string(name: 'SERVICE', defaultValue: 'Frontend', description: 'The service to build and test')
        string(name: 'BRANCH_NAME', defaultValue: 'main', description: 'Branch name')
    }
    environment {
        CONFIG = readYaml file: "${params.SERVICE}/dev.yaml"
    }
    stages {
        stage('Checkout Code') {
            steps {
                script {
                    git branch: params.BRANCH_NAME, url: "https://github.com/SwiftPix/${params.SERVICE}.git"
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t ${params.SERVICE}:${params.BRANCH_NAME} .'
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'docker run --rm ${params.SERVICE}:${params.BRANCH_NAME} npm install'
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    sh 'docker run --rm ${params.SERVICE}:${params.BRANCH_NAME} npm run build'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'docker run --rm ${params.SERVICE}:${params.BRANCH_NAME} npm test'
                }
            }
        }
    }
}
