kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: geoloc-service
  namespace: swiftpix
  labels:
    app: geoloc-service
    app.kubernetes.io/component: geoloc-service
    app.kubernetes.io/instance: geoloc-service
    app.kubernetes.io/name: geoloc-service
    app.kubernetes.io/part-of: Triggers
  annotations:
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-uri: 'https://github.com/SwiftPix/Geoloc-service'
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - geoloc-service
        from:
          kind: ImageStreamTag
          namespace: swiftpix
          name: 'geoloc-service:latest'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: geoloc-service
    deploymentconfig: geoloc-service
  template:
    metadata:
      labels:
        app: geoloc-service
        deploymentconfig: geoloc-service
    spec:
      containers:
        - name: geoloc-service
          image: 'image-registry.openshift-image-registry.svc:5000/swiftpix/geoloc-service:latest'
          envFrom:
            - configMapRef:
                name: geo-loc
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
